### ISSUE TITLE
Freaky ocean/river/beach biome colour patches (dark and light blue checker pattern)

### ISSUE THREAD

**Issue by AriinPHD** [kormic911/EvilOcean#4]
The "river" biome is causing very visible bright blue patches of ocean all over the place (in the same fashion as ice is spawned in). Seems to happen whenever oceans, rivers and beaches are involved and/or near land/islands.

See screenshot. In this example, the pure blue (non-error area) in the outer edge is ocean, the dark blue in the middle is also ocean, the strange checker-area around the dark blue part is a mix of ocean (dark), river and beach (both light blue) biomes...

Pretty strange.

When loading new worlds, sometimes you spawn in a huge "problem-free" area and have to trave for several minutes before encountering the issue; other times you spawn practically in the middle of it.

![2016-09-22_22 01 26](https://cloud.githubusercontent.com/assets/5846389/18764180/95b5adb0-8110-11e6-9b37-981ab74abe31.png)

**Comment by kormic911** [comment]
Thanks for the report AriinPHD, I have been working on a solution to correct this but havent finished it up just yet. I think the end solution should be to just remove the river biome since its not really used (at least not properly) to hopefully prevent that crazyness

**Comment by kormic911** [comment]
Fixed in most recent commit. (1.10.2-1.0.1, 1.8.9-1.0.1, 1.7.10-1.0.3)
