### ISSUE TITLE
mob spawning problems (ive posted this on curseforge btw :3 )

### ISSUE THREAD

**Issue by monkeybee11** [kormic911/EvilOcean#7]
ive noticed that water mobs like squid and fishy mobs from mocreacher ...

and aqua creepers form the aquacreeper mod arnt spawning in the colourfull ocean biomes S:

 

is this a bug or inteded behavour?

 

and any idea where im able to get a list of biomes with there names so im able to add them to the monsters inside custom mob spawner config to fix this if it is a bug :P

 

1.10 minecraft  some of the required mods arnt 1.11 yet :(

**Comment by kormic911** [comment]
hey @monkeybee11 here is that list you asked for:

`eo_ocean
eo_deep_ocean
desert_ocean
mountain_ocean
forest_ocean
taiga_ocean
jungle_ocean
birch_forest_ocean
roofed_forest_ocean
mesa_ocean
mega_taiga_ocean`

Now that I know what version is having the problems, I can investigate further.

**Comment by monkeybee11** [comment]
ty

**Comment by kormic911** [comment]
I released a new version for 1.10.2 and 1.11.2 that should fix the issues with mob spawning, let me know if it works better for you now.
